variables:
  NODE_VERSION: "12"
  FOO: "initial foo"
  BAR: "initial bar"
  BAZ: "initial baz"

image: node:lts-alpine3.12

cache:
  key: ${CI_COMMIT_REF_SLUG}
  #untracked: true
  policy: pull
  paths:
    - node_modules

stages:
  - pre-prepare
  - prepare
  - test
  # - build
  # - deploy
  # - schedule

include:
  - local: "/ci/prepare.yml"
  # - local: '/ci/test.yml'
  # - local: '/ci/schedule.yml'
  # - local: '/ci/build.yml'
  # - local: '/ci/deploy.yml'

pre:
  stage: pre-prepare
  before_script:
    - apk add --no-cache git
  script:
    - mkdir -p test1
    - touch test1/test.txt
    - git status
  artifacts:
    paths:
      - test1

test:unit:
  stage: test
  before_script:
    - echo "Yay before script !"
  script:
    - ls node_modules
  after_script:
    - echo "Yay after script !"
  dependencies:
    - install

failingjob:
  stage: test
  script:
    - echo 1
    - echo 2
    - node -e "process.exit(1);"
    - echo 3
